name: Echo Hello World

on:
    push:
        branches:
            - main

jobs:
    echo_hello_world:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Echo Hello World
              run: echo "Hello World"