name: Deploy to Linux Server

on:
  push:
    branches:
      - main

env:
  SERVER_SCRIPT: |
    echo ${{secrets.SERVER_HOST}} >> /home/ubuntu/hello.txt
    echo "ragu G is here" >> /home/ubuntu/hello.txt
    echo "Script executed successfully"
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Echo Hello World
        run: echo "Hello World"

      - name: Deploy Code
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: eval "${{ env.SERVER_SCRIPT }}"
            