name: Deploy to Linux Server

on:
  push:
    branches:
      - main

env:
  SERVER_SCRIPT: |
    # check hello.txt file is exist or not
    if [ -f hello.txt ]; then
      echo "File is exist"
    else
      echo "File is not exist"
    fi
    echo "Task Completed"
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Echo Hello World
        run: echo "Hello World"

      - name: Deploy Code
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu
            ${{ env.SERVER_SCRIPT }}
            